USE taskboard;

CREATE TABLE IF NOT EXISTS `BOARD_COLUMNS`(
    `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `BOARD_ID` BIGINT(20) NOT NULL,
    `NAME` VARCHAR(255) NOT NULL,
    `ORDER` INT(11) NOT NULL,
    `KIND` VARCHAR(7) NOT NULL,
    CONSTRAINT `FK_BOARD_COLUMNS_BOARD_ID` FOREIGN KEY (`BOARD_ID`) REFERENCES `BOARDS` (`ID`)
)ENGINE=INNODB;