CREATE TABLE IF NOT EXISTS `BLOCKS`(
    `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `CARD_ID` BIGINT(20) NOT NULL,
    `BLOCK_REASON` VARCHAR(255) NOT NULL,
    `UNBLOCK_REASON` VARCHAR(255) NOT NULL,
    `BLOCKED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `UNBLOCKED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT `FK_BLOCKS_CARDS_ID` FOREIGN KEY (`CARD_ID`) REFERENCES `CARDS` (`ID`)
)ENGINE=INNODB;